### ISSUE TITLE
Async select changes the case of input when ignoreCase is false

### ISSUE THREAD

**Issue by scags9876** [JedWatson/react-select#1106]
Here is a plunkr that demonstrates the issue https://plnkr.co/edit/i947CSpI44PuVxx7wsT8?p=preview

Begin typing 'O', then 'n'   After the options are loaded, the input is altered to now contain 'on' instead of 'On'.   Though filtering is case insensitive, we would like to not alter the case of the string the user enters.

This is a change in behavior from 1.0.0-beta13 to 1.0.0-beta14.

Great job by the way, I'm loving react-select 👍

**Comment by ConneXNL** [comment]
Same problem here. You cannot set ignoreCase to false because this will break the react-select cache lookup.

**Comment by traumatic** [comment]
Hi,
Correct me if I am wrong but this issues just becomes more important considering the newly AsyncCreatable component.
Use Case: A user types in "Test" into a AsyncCreatable component. The component converts "Test" to "test" and shows a list of option (e.g. "Electrical tester", "Unit tester", etc.). However, instead of selecting one of the given options the user intended to create/add the entry "Tester, Software", which is low-case now.

Thanks

**Comment by saviomuc** [comment]
It would be really great if this could be fixed. There really should be no reason to change the case of the displayed input.

**Comment by sebslomski** [comment]
This PR works perfectly. Is there anything that prevents it from being merged? Can I help somewhere?

**Comment by kauffecup** [comment]
@sebslomski as @TheSharpieOne pointed out in the PR that I opened, an extra prop shouldn't be required to fix the issue. There is currently an error in the logic which should be fixed - instead of band-aiding that by adding more props, we should instead fix that logic! I've been out of town the past two weeks so haven't had time to update my PR but I will soon!

**Comment by saviomuc** [comment]
@kauffecup I agree with @TheSharpieOne. It makes a lot of sense to fix the logic instead of adding another prop. I think you are referring to this updated PR https://github.com/JedWatson/react-select/pull/1329 right? Looks good to me. Hopefully it gets merged soon. =)

**Comment by saviomuc** [comment]
Btw. In the meantime as a workaround I set `filterOption={() => true}` which basically disables the filter functionality (which is already handled by another component anyway). At least for me this works.

**Comment by djthayer** [comment]
I'm using the latest rc5 version and this is still an issue for AsyncCreatable.  As others have said `ignoreCase = false` isn't an option when you want the `Async` portion to be case insensitive but the `Creatable` portion to not be.  Seems like this should be an easy fix.  @JedWatson Can you provide an update on when this could be corrected?  Thanks!

**Comment by DanielMcDonald** [comment]
Just want to confirm what @djthayer stated. I'm using the latest version and this problem remains.

**Comment by xiaolin** [comment]
I'm having a similar issue where I adjusted `ignoreCase` to `false` so that options can be created with case insensitivity. The problem seems to be that `ignoreCase` is used in `filterOptions` and `_onInputChange`, causing a conflict when I don't care about case sensitivity for results matches, but do care about case sensitivity for creations.

https://github.com/JedWatson/react-select/blob/8631d18a045ab9d7a0a6ce502d31af7bc621e798/src/Async.js#L145

https://github.com/JedWatson/react-select/blob/916ab0e62fc7394be8e24f22251c399a68de8b1c/src/utils/defaultFilterOptions.js#L24

The two lines above are conflicting with each other, when using `AsyncCreatable`

**Comment by gwyneplaine** [comment]
As stated above, #1858 is a fix for this issue, and has been merged, closing this issue
