### ISSUE TITLE
Select.Async does not call onInputChange

### ISSUE THREAD

**Issue by bmamouri** [JedWatson/react-select#1283]
I am trying to implement this [demo](https://github.com/JedWatson/react-select/blob/master/examples/src/components/CustomRender.js) using Select.Async.

The event `onInputChange` does not call in the `Select.Async` component, but it works fine in the `Select` component itself.

**Comment by kr0** [comment]
This is related to [https://github.com/JedWatson/react-select/pull/1231](this) . There is a simple fix it seems. This change hasn't been pulled.

**Comment by kr0** [comment]
I added the changes manually for right now and it works. In the Async component, there is no call to this.props.onInputChange .

**Comment by kr0** [comment]
Plot thickens.. When I import using var react-select = require("react-select") I get definitions from the react-select/lib folder. These don't reflect the src folder. This is a problem because it's in the src folder that the onInputChange issue was resolved.

**Comment by kr0** [comment]
I opted to use 1.0.0-rc.1 instead of rc.2

**Comment by aminmc** [comment]
This seems to be still an issue in rc.2 downgrading to rc.1 works.

**Comment by mhubenthal** [comment]
I am seeing this issue as well for the `Creatable` component. The bug lies on these lines in that component:
```javascript
onInputChange (input) {
	const { onInputChange } = this.props;

	if (onInputChange) {
		onInputChange(input);
	}

	// This value may be needed in between Select mounts (when this.select is null)
	this.inputValue = input;
}
```
Even though `onInputChange()` is called, the value is not *returned*. When I just use the `Select` component I am able to apply a masking function, whereas when using the `Creatable` component, that masking function value is never returned from the `Creatable` `onInputChange` call to the `Select` component. The function passed in as a prop *is* called, but the value is never returned up the call stack.

The correct code would look like this:
```javascript
onInputChange (input) {
	const { onInputChange } = this.props;

	// This value may be needed in between Select mounts (when this.select is null)
	this.inputValue = input;

	if (onInputChange) {
		return onInputChange(input);
	}
}
```
cc: @JedWatson

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you feel this issue / pull request is still relevant and you'd like us to review it, please leave a comment and we'll do our best to get back to you.
