### ISSUE TITLE
Limit on multiselect

### ISSUE THREAD

**Issue by digitalmio** [JedWatson/react-select#1341]
Hello,

Is there any way of limiting amount of options available for user to choose?
Lets say I have a list of 30 elements, but user can choose maximum of 5.

I'm using v0.9, any help would be appreciated.
Thanks.

**Comment by gpbl** [comment]
I am also looking for this. For now, my workaround is to reset the options prop by checking the length of the current values array:

```jsx
<ReactSelect
  multi
  value={this.state.values}
  options={
    this.state.values.length >= 2 ? 
      this.state.values : 
      selectOptions
  }
  onChange={values => this.setState({ values })}
/>
```

it's not an optimal solution (i'd like at least to remove the menu arrow). Has anybody found another way?

**Comment by nicknmejia** [comment]
Can we please get a better answer to this?  I've found other closed issues referencing this saying its doable (specifically #174 ) but the docs don't specify a limiter ANYWHERE.

**Comment by Gelareh** [comment]
Any solutions?

**Comment by nicknmejia** [comment]
My solution for this was similar to @gpbl's solution

On change I would check if the number of items created is less than 5 (the amount I allow), and to only update the state if it was.  See code below.

`if ( value.length <= 5 ) {
            this.setState( {
                value: value
            } );
            this.handleTags( value )
        }

`

**Comment by Gelareh** [comment]
Thank you @nicknmejia! I used your solution and it worked properly.

**Comment by cheerWang** [comment]
When I change the onChange function ，I can't clear the selected option.
Do you have the same question?
```javascript
function RCSelect(props) {
  const { input, maxValLength } = props;
  const onChange = (value) => {
    if (maxValLength && input.value && input.value.split(',').length >= maxValLength) {
      value = input.value.split(',').slice(0, maxValLength).join(',');
      input.value = value;
    } else {
      input.onChange(value);
    }
  };
  return (
    <Select
      {...props}
      value={input.value}
      onChange={onChange}
      onBlur={() => input.onBlur(input.value)}
      options={props.options}
      simpleValue
    />
  );
}
```

**Comment by moshfeu** [comment]
Open for 2.5 years :(

**Comment by Rall3n** [comment]
I do not see the need for an extra option on the component. If you need it as a prop, then just create a simple wrapper around the `Select` component.

```jsx
const LimitedSelect = ({ valueMax, onChange, ...props }) => {
    const onChangeWithLimit = React.useCallback((value, actionMeta) => {
        if (props.isMulti && valueMax && (Array.isArray(value) && value.length > valueMax))
            return;  

        if (onChange) {
            return onChange(value, actionMeta);
        }
    }, [limit])

    return <Select {...props} onChange={onChangeWithLimit} />
}
```

----
For `v1.x` we need a different approach for `onChange`:
```jsx
const onChangeWithLimit = React.useCallback((value) => {
    var delimiterRegex = new RegExp(props.delimiter || ',', 'g');
    if (props.multi && valueMax) {
        var valueLength = Array.isArray(value) ? value.length : (value.match(/,/g) || []).length;
        if (valueLength > valueMax) return;
    }  

    onChange && onChange(value);
}, [limit])
```

**Comment by alfred-pb** [comment]
@Rall3n do you mind providing a codesandox? I didn't understand your solution

**Comment by moshfeu** [comment]
@alfred-pb you can see how we implemented somethink like that here: https://github.com/Coding-Coach/find-a-mentor/blob/6b347e5042d374430a29546bc83e419f82367a99/src/components/MemberArea/EditProfile.js#L116

**Comment by hrafaelveloso** [comment]
I'm using one Creatable multiselect, and to mitigate this issue I'm using this:
```jsx

const MultiCreatable = ({ options, handleChange, handleCreate, value, maxOptions }) => {
  return (
    <CreatableSelect
      isMulti
      placeholder={placeholder}
      onChange={handleChange}
      options={value.length === maxOptions ? [] : options}
      noOptionsMessage={() => {
        return value.length === maxOptions ? 'You've reached the max options value' : 'No options available' ;
      }}
      onCreateOption={handleCreate}
      value={value}
    />
  )
}
```

**Comment by yazeed** [comment]
> I'm using one Creatable multiselect, and to mitigate this issue I'm using this:
> 
> ```js-jsx
> const MultiCreatable = ({ options, handleChange, handleCreate, value, maxOptions }) => {
>   return (
>     <CreatableSelect
>       isMulti
>       placeholder={placeholder}
>       onChange={handleChange}
>       options={value.length === maxOptions ? [] : options}
>       noOptionsMessage={() => {
>         return value.length === maxOptions ? 'You've reached the max options value' : 'No options available' ;
>       }}
>       onCreateOption={handleCreate}
>       value={value}
>     />
>   )
> }
> ```

I've corrected your options and noOptionsMessage for when the length on the multiselect is actually 0 making selectedOptions null in that case.

`options={
                            selectedOptions == null
                                ? descriptionOptions
                                : selectedOptions.length === maxOptions
                                ? []
                                : descriptionOptions
                        }
noOptionsMessage={() => {
                            return selectedOptions == null
                                ? false
                                : selectedOptions.length === maxOptions
                                ? "You've reached the max number of options."
                                : "No options available";
                        }}`

**Comment by wassimbj** [comment]
For future guys, i solved it like this: 
```javascript
<Select
 closeMenuOnSelect={false}
 components={makeAnimated()}
 isMulti
 isSearchable
 name='topics'
 options={topicsOptions}
 onChange={(v) => {
  // here i dont want the user to choose more then 3 topics
      if(v== null || v.length < 4){
        formik.setFieldValue('topics', v);
      }
  }}
 value={formik.values.topics}
/>
```

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our efforts towards the current major version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by edi** [comment]
@bladey upgrading to the latest major version still does not sort this issue. There's no easy solution to have a limit of values you can select ... not sure what's holding you back to add such a trivial feature?

Great library btw.

**Comment by victoralvesp** [comment]
If someone is using Async Select, one could add a limiting function to isOptionDisabled prop that checks for the number of selected items, like so:
```tsx
    selectedItems: Array<any> = [];
    handleSelectChange(eventValue: any, params: any): void {
        if (typeof params === typeof undefined)
            return;

        let { action, option, removedValue } = params;
        if (action === "select-option" && typeof option !== typeof undefined) {
            if (this.selectedItems.length == MAXIMUM_SIZE) {
                this.showErrorMessage();
                return;
            }
            let { label } = option;
            if (typeof label !== typeof undefined) {
                this.selectedItems = [...this.selectedItems, label];
            }
        }
        else if (action === "remove-value" && typeof removedValue !== typeof undefined) {
            let { label } = removedValue;
            if (typeof label !== typeof undefined) {
                const index = this.selectedItems.indexOf(label, 0);
                if (index > -1) {
                    this.selectedItems.splice(index, 1);
                    this.selectedItems = [...this.selectedItems];
                }
            }
        }
    }
    maximumReached(option: any, options: OptionsType<any>): boolean {
        if (this.selectedItems.length === MAXIMUM_SIZE)
            return true;
        return false;
    }
    render() {
        return (

            < AsyncSelect
                isOptionDisabled={this.maximumReached.bind(this)}
                onChange={this.handleSelectChange.bind(this)}
            />

        );
    }
```

**Comment by Hawstein** [comment]
@hrafaelveloso Great Solution! Thanks for sharing.

I modified your version since I wanted to disable the remaining options once the limit was reached. Here is the code:

```javascript
const MultiSelect = ({valueList, onChange, options, maxLimit = 100}) => {
  return (
    <Select
      value={valueList}
      isMulti
      onChange={onChange}
      options={options}
      isOptionDisabled={(option) => valueList.length >= maxLimit}
    />
  );
};
```

**Comment by guilhermebellotti** [comment]
> @hrafaelveloso Great Solution! Thanks for sharing.
> 
> I modified your version since I wanted to disable the remaining options once the limit was reached. Here is the code:
> 
> ```js
> const MultiSelect = ({valueList, onChange, options, maxLimit = 100}) => {
>   return (
>     <Select
>       value={valueList}
>       isMulti
>       onChange={onChange}
>       options={options}
>       isOptionDisabled={(option) => valueList.length >= maxLimit}
>     />
>   );
> };
> ```

Good idea @Hawstein !
Maybe it's not the best thing to do, but in my case I solved it this way (hard code)

```js
<Select
   isMulti
   closeMenuOnSelect={false}
   placeholder="Selecione a(s) marca(s)"
   options={options}
   isOptionDisabled={(params) =>
      document.querySelectorAll(".css-1rhbuit-multiValue").length >= 3
   }
   selectProps
/>
```

Checking how many were selected through the class react-select uses

**Comment by u-uysal** [comment]
How can We make disable the rest of options? @Hawstein @wassimbj @yazeed @Rall3n

**Comment by Stesic** [comment]
The limit can be set with custom styles....Example bellow

`<ReactSelect
        key={defaultValues}
        value={defaultValues}
        isMulti
        onChange={(options, event) => {
          handleChange(options, event);
        }}
        instanceId={name}
        placeholder={placeholder}
        name={name}
        options={options}
        className="basic-multi-select-brand"
        classNamePrefix="select-brand"
        styles={customStyles} 
      />
  
  const customStyles = {
  control: (base, state) => {
    const limitReached = state.selectProps.value?.length >= 3;
    return {
      ...base,
      '.select-brand__dropdown-indicator': {
        display: `${limitReached ? "none" :  "flex"}`
      }
    };
  },
};
`

**Comment by elewin** [comment]
It would be great if this was supported nativly without all these workarounds, just a `multiLimit` prop or something like that, and then it would prevent adding more text input to search or clicking more items to select
