### ISSUE TITLE
[v2] Touch Support - multiselect removing and selection broken

### ISSUE THREAD

**Issue by Slind14** [JedWatson/react-select#2521]
**Version** `2.0.0-alpha.8`
**React** `15.6.2`

When using the multiselect from v2 on touch devices, removing of tags doesn't work at all and selecting tags often doesn't save.

**Comment by Slind14** [comment]
Due to https://github.com/JedWatson/react-select/issues/2522 I can't test this with anything newer than alpha 8.
Is reproduce-able with chromes device toolbar.
[![Edit 91proo9354](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/91proo9354)

**Comment by usernamus** [comment]
@Slind14, I fixed this problem https://github.com/usernamus/react-select/commit/169731a5fc1eda2da29db37ba51bcd50db87dfa8, but I'm not sure that this solution is true on 100%

**Comment by bladey** [comment]
Hello -

In an effort to sustain the `react-select` project going forward, we're closing old issues / pull requests.

We understand this might be inconvenient but in the best interest of supporting the broader community we have to direct our limited efforts to maintain the latest version.

If you aren't using the latest version of `react-select` please consider upgrading to see if it resolves any issues you're having.

However, if you feel this issue / pull request is still relevant and you'd like us to review it - please leave a comment and we'll do our best to get back to you!

**Comment by Slind14** [comment]
This is still a thing and a major incompatibility with mobile devices. It would be great if you could consider re-opening it.

**Comment by bladey** [comment]
Thanks @Slind14!

**Comment by ebonow** [comment]
Greetings @Slind14 

I have verified that the alpha version you provided in your sandbox is behaving unexpectedly as you described, but when changing the version to V2.4.4, I no longer had issues removing multiValues nor is this an issue in V3. 

[Here is a fork of your sandbox using V2.4.4](https://codesandbox.io/s/react-select-v2-multi-value-remove-ontouch-9z5mz)

Please verify that it still isn't working and we can reopen and continue to investigate.
