### ISSUE TITLE
v3 prop className did not match warning in Next.js

### ISSUE THREAD

**Issue by vaunus** [JedWatson/react-select#3590]
Hi. I am seeing a warning since upgrading to version 3 with the latest versions of Next.js and React:

`Warning: Prop className did not match. Server: "css-1g6gooi" Client: "css-w8afj7-Input"`

See this sandbox for my reproduction:
https://codesandbox.io/s/helloworld-g1mb7

**Comment by tomlagier** [comment]
Same issue outside of Next.js, but when SSR'd. Using `"react-select": "^3.0.4"`, getting the same error.

**Comment by ulysset** [comment]
Any news on this one? Could it be because of emotion?

**Comment by irvelervel** [comment]
Using Next.js and `"react-select": "^3.0.4"`, getting the same error.

**Comment by symbiane** [comment]
Warning: Prop `className` did not match. Server: "css-1g6gooi" Client: "css-w8afj7-Input"
warningWithoutStack @ react-dom.development.js:506

**Comment by z3niths** [comment]
I've experienced the same problem

<img width="1162" alt="Screen Shot 2562-07-01 at 03 33 29" src="https://user-images.githubusercontent.com/16873595/60401823-2263e700-9bb1-11e9-9531-6533bf6916d0.png">

**Comment by dicrescenzoa** [comment]
same problem here as well, any idea? 🤔

**Comment by dydokamil** [comment]
The quick and dirty fix for it is to import the component dynamically. If using next.js you can:
`const SelectInput = dynamic(() => import('react-select'));`

**Comment by boscomateo** [comment]
Same here

**Comment by maciejmatu** [comment]
I also have this issue. It seems that on the client the components have a different label configuration, because on the backend there is no `-Input` suffix. Is it possible that emotion uses some kind of an env variable to determine what label format to use? I tried setting different `NODE_ENV` but it doesn't seem to change anything :/

**Comment by maciejmatu** [comment]
Okay, I found out what is the problem! In `package.json` file of `react-select` package, there are those two fields:
![image](https://user-images.githubusercontent.com/10004167/62356764-1b165d00-b512-11e9-9119-2596a87d9039.png)

Turns out that next.js selected different module types for different environments. It loaded `react-select.cjs.js` file for **node** and `react-select.browser.esm.js` for **browser**. I'm not exactly sure **why** the code in different modules resulted in different classNames (maybe it is connected to different env variables or something else, but I didn't investigate further). 

For now the quick fix I found in [this thread](https://github.com/webpack/webpack/issues/5756#issuecomment-405468106) is to change the `resolve` field for webpack config to prioritize `main` field over `module`  when building a bundle. 

example: 
```javascript
// next.config.js
module.exports = {
  resolve: { mainFields: ["main", "module"] }
};
```

The downside is that it can break other packages that must prioritize `module`, but in my case (for now at least) it fixed this issue. It would be great if someone who understand the codebase further could look into this and help out a bit 😄

**Comment by armedian** [comment]
Looks like disabling SSR for a particular component works.
https://codesandbox.io/s/hello-world-gox8w

**Comment by gwyneplaine** [comment]
> Okay, I found out what is the problem! In `package.json` file of `react-select` package, there are those two fields:
> ![image](https://user-images.githubusercontent.com/10004167/62356764-1b165d00-b512-11e9-9119-2596a87d9039.png)
> 
> Turns out that next.js selected different module types for different environments. It loaded `react-select.cjs.js` file for **node** and `react-select.browser.esm.js` for **browser**. I'm not exactly sure **why** the code in different modules resulted in different classNames (maybe it is connected to different env variables or something else, but I didn't investigate further).
> 
> For now the quick fix I found in [this thread](https://github.com/webpack/webpack/issues/5756#issuecomment-405468106) is to change the `resolve` field for webpack config to prioritize `main` field over `module` and `browser` when building a bundle.
> 
> example:
> 
> ```js
> // next.config.js
> module.exports = {
>   webpack: config => {
>     config.resolve.mainFields = ["main", "browser", "module"];
>     return config;
>   },
> };
> ```
> 
> The downside is that it can break other packages that must prioritize `module`, but in my case (for now at least) it fixed this issue. It would be great if someone who understand the codebase further could look into this and help out a bit 😄

thanks for the insight into the problem @maciejmatu, @mitchellhamilton any ideas on how to fix this issue for our next js users?

**Comment by mitchellhamilton** [comment]
Fixed this with an update to some regex in emotion. An example of it working by reinstalling react-select so the new version of emotion is used: https://codesandbox.io/s/hello-world-jtyix

**Comment by JStein92** [comment]
> Fixed this with an update to some regex in emotion. An example of it working by reinstalling react-select so the new version of emotion is used: https://codesandbox.io/s/hello-world-jtyix

Still getting this error in 3.1.0

**Comment by ciruz** [comment]
I'm also experiencing the same error now with `react-select 3.1.0` and the latest `next.js` version `9.4.4`.

**Comment by RickyMarou** [comment]
Using `react-select 3.1.0` in a react app that uses SSR (not using next.js but ssr custom made using `@loadable` and `react-router`) and still getting the error 😞 .
I guess we will be disabling SSR for that component, which is an okay solution for us 🤷

**Comment by marklawlor** [comment]
Setting the `inputId` and `instanceId` props fixed the issue for me (you can see it demonstrated in the codesandbox by @mitchellhamilton).

It would be nice for this library to provide a `ssr: true` option that would automatically generate these values. Otherwise you can set them yourself either via

- Roll your own random generator
- https://github.com/thearnica/react-uid
- [Wait for a potential official uid generator](https://github.com/facebook/react/issues/5867#issuecomment-678267054)

**Comment by bladey** [comment]
Thanks for the feedback all, we'll look into this.

**Comment by MitchWeiss** [comment]
Hey @bladey, just wondering if you've had a chance to look into this by any chance?

**Comment by laleksiunas** [comment]
I can reproduce this hydration mismatch only on Safari browsers (both macOS and iOS) which is rather strange. Trace:
```
Warning: Prop `className` did not match. Server: "css-b8ldur-Input" Client: "css-19odofu-Promise"
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by Input)
    in Input (created by Select)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by ValueContainer)
```

**Comment by Methuselah96** [comment]
I've started [a fork](https://github.com/react-select-oss/react-select) of react-select. Feel free to resubmit this issue on the fork and/or submit a PR to resolve this issue on the fork and we can get it merged and released.

**Comment by mediabeastnz** [comment]
👀

**Comment by j-fan** [comment]
I am seeing this issue in react-select v4.1 with React SSR, but it is only affecting Safari. Does anyone have any insights on this?
Here is a simple reproduction: https://codesandbox.io/s/react-ssr-bug-hfp29?file=/src/components/App.jsx
```
Warning: Prop `className` did not match. Server: "css-b8ldur-Input" Client: "css-1g6gooi"
```

**Comment by marklawlor** [comment]
> I am seeing this issue in react-select v4.1 with React SSR, but it is only affecting Safari. Does anyone have any insights on this?
> Here is a simple reproduction: https://codesandbox.io/s/react-ssr-bug-hfp29?file=/src/components/App.jsx
> 
> ```
> Warning: Prop `className` did not match. Server: "css-b8ldur-Input" Client: "css-1g6gooi"
> ```

Have you tried setting both `inputId` and `instanceId` as per earlier comments & this example https://codesandbox.io/s/hello-world-jtyix

**Comment by ebonow** [comment]
Greetings @j-fan ,

Confirmed. I was able to replicate the bug, but only when using Safari browser.

@marklawlor - an instanceId was provided and adding an inputId did not impact the outcome.

I will open a bug report with Emotion and see if they might be able to identify the cause.

<img width="800" alt="Screen Shot 2021-02-11 at 9 45 07 PM" src="https://user-images.githubusercontent.com/1007579/107734503-6f2b0180-6cb2-11eb-9ab7-6273fe207143.png">

**Comment by everblaze** [comment]
any movement on this im use Remix and have this same issues, I have added instanceId and InputId but still have this error with SSR

`Warning: Prop `className` did not match. Server: "css-b8ldur-Input"`

**Comment by Methuselah96** [comment]
This seems like an issue that people keep running into. I'm planning to take a look at this as my next area of focus (along with https://github.com/JedWatson/react-select/issues/4088) to see what's going on and what we can do to resolve it. Thank you all for your patience.

**Comment by Methuselah96** [comment]
See https://github.com/emotion-js/emotion/issues/2255 for the latest on this. Since it's been confirmed that this is not a production-impacting issue I'm taking this off the 5.1 milestone. https://github.com/JedWatson/react-select/issues/4088 is more important and is where I'll focus my efforts.

**Comment by shehi** [comment]
This problem is happening on Chrome and FF with NextJS, when component is SSR'ed.

![image](https://user-images.githubusercontent.com/653569/154818945-47dc2b31-9875-4cff-85da-9eeb194ad927.png)

**Comment by laleksiunas** [comment]
@shehi I think you are experiencing a different problem. Try setting an _instanceId_ prop.

**Comment by jakexconniff** [comment]
Having this same issue with Remix, React-Select v5.2.2 on Google Chrome, so it is definitely not Safari. I have set inputId and instanceId.

```react-dom.development.js:67 Warning: Prop `className` did not match. Server: " css-6j8wv5-Input" Client: " css-ujecln-Input2"```

is what the error message switches to once I add instanceId.

**Comment by jdnichollsc** [comment]
> It's not really a fix, but you can wrap with a `<ClientOnly>` HOC such as this https://www.joshwcomeau.com/react/the-perils-of-rehydration/#abstractions

But what happen if I want to have different classes using SSR? I mean, I'm adding classes using Media Queries with [react-responsive](https://www.npmjs.com/package/react-responsive) package but I don't see a good alternative to know that info from server side (I'm using RemixJS) 🤔

**Comment by richpixel** [comment]
I was hoping that setting prop `classNamePrefix` would dismiss the warning, but it looks like it still generates a uid for Input:

`Warning: Prop `className` did not match. Server: "tags-select__input-container css-6j8wv5-Input" Client: "tags-select__input-container css-ujecln-Input2"`

**Comment by NiklasAbrahamsson** [comment]
Sadly I am having this issue as well and since there doesn't seem to be a viable fix for it yet, i will go with the <ClientOnly> soultions for now. Will have to come back to this later.

**Comment by tyteen4a03** [comment]
Same issue here with Remixc.

**Comment by pogran** [comment]
I think its the best resolution for now

`	if (!isMounted) {
		return <></>;
	}`

**Comment by EvgeniyBudaev** [comment]
**Fix in Remix.js**

```python
import { useHydrated } from 'remix-utils'; 
const isHydrated = useHydrated();  
isHydrated ? <Select /> : null;  
```


**Fix in Next.js and React.js**

```python
import { useEffect, useState } from "react";

export const useMounted = (): { hasMounted: boolean } => {
  const [hasMounted, setHasMounted] = useState(false);
  useEffect(() => {
    setHasMounted(true);
  }, []);
  return { hasMounted };
};

const { hasMounted } = useMounted();

hasMounted ? <Select /> : null;
```

**Comment by phifa** [comment]
@EvgeniyBudaev the thing is, this causes a layout shift. Is it not possible to server side render react-select?

**Comment by EvgeniyBudaev** [comment]
@phifa Layout shift due to nulls. This is just an example. Instead of nulls, there can be an element with the same dimensions as select. I didn't make the example complicated. The main idea in solving the problem of server and client hydration.

**Comment by phifa** [comment]
@EvgeniyBudaev Yeah i know, my question is, can the component simply not render on the server?

**Comment by nick-bigger** [comment]
hey all, is there any movement on this issue ? I don't see any truly viable solution here - we have tons of ReactSelects across our application - is the only solution to wrap _all_ of them in a conditional ? Not only is this tedious and poor DX, it means the initial server code will be missing all of the inputs and then they'll all suddenly pop in.

**Comment by nick-bigger** [comment]
hey all, is there any movement on this issue ? I don't see any truly viable solution here - we have tons of ReactSelects across our application - is the only solution to wrap all of them in a conditional ? Not only is this tedious and poor DX, it means the initial server code will be missing all of the inputs and then they'll all suddenly pop in.

**Comment by cluk3** [comment]
It happens the same to me using Remix. It only happens in development though, I'm pretty sure the main reason is because in development emotion suffixes the generated className with the displayName of the component, and for some reason the on the client the display name of react-select components change from `${Component.displayName}` to `${Component.displayName}2` as you can see yourself in the following example error:

```
Warning: Prop className did not match. Server: "tags-select__input-container css-6j8wv5-Input" Client: "tags-select__input-container css-ujecln-Input2"
```

**Comment by jeffminsungkim** [comment]
Any updates on this thread?
I'm having the same issue on Safari.

react-select v5.7.3 react v18.2.0

**Comment by brenoprata10** [comment]
I am also having the same issue.

**Comment by mikkpokk** [comment]
`<ClientOnly>` "fix" is not really fix. It causes layout shifts. Unless you use that component below the fold, layout shifts are not acceptable nowadays, it's UX nightmare.

**Comment by ZeldOcarina** [comment]
It keeps saying it's closed on this thread but the issue continues.. it has been three years now..

**Comment by ZeldOcarina** [comment]
Same issue on Astro.

**Comment by oskarhertzman** [comment]
Getting similar error when using isSearchable={true}

```javascript
hydration-error-info.js:63 Warning: Prop `className` did not match. Server: "css-1czm0f-dummyInput-DummyInput" Client: "css-mohuvp-dummyInput-DummyInput"
```

```javascript
 <ReactSelect
          ...
            isSearchable={isSearchable}

```

**Comment by imraann00** [comment]
> Getting similar error when using isSearchable={false}
> 
> hydration-error-info.js:63 Warning: Prop `className` did not match. Server: "css-1czm0f-dummyInput-DummyInput" Client: "css-mohuvp-dummyInput-DummyInput"
>  <ReactSelect
>           ...
>             isSearchable={false}

getting this exact same error - did you manage to find a solution for this?
